### ISSUE TITLE
user-can-see-their-car

### ISSUE THREAD

**Issue by vkalinkin** [vkalinkin/driving-game#1]
# Feature

User can see their car.

## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create a car object in JS
- [x] Create an appear method to the car object
- [x] Create myCar instance of car object
- [x] Have car image visible on HTML page and assign it to myCar
- [x] Make sure car image is positioned in the very top left
- [x] Make sure car is oriented in the correct direction
- [x] Set background color of page to green

## Example

![user can see their car](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/demos/driving-game/user-can-see-their-car.png)
