### ISSUE TITLE
user-can-turn-their-car

### ISSUE THREAD

**Issue by vkalinkin** [vkalinkin/driving-game#2]
# Feature

User can turn their car.

## Hints!

- Create a simple data model that includes which way the car is facing, (north, south, east, or west).
- Listen for `'keydown'` events on the `document`.

## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a direction variable
- [x] Add event listeners that listen for the arrow keys and change the direction variable
- [x] Change the rotation of the car by changing the styling based on the direction variable
- [x] Add transitions to the rotation of the car image

## Example

![user can turn their car](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/demos/driving-game/user-can-turn-their-car.gif)
