### ISSUE TITLE
user-can-start-their-car

### ISSUE THREAD

**Issue by vkalinkin** [vkalinkin/driving-game#3]
# Feature

User can start their car.

## Hints!

- Add a location to your data model to hold the car's `x` and `y` coordinates on the page.
- Use absolute positioning for your image.
- [Use the `style` property](https://developer.mozilla.org/en-US/docs/Web/API/ElementCSSInlineStyle/style) of element objects to change your car's `top` and `left` box offset styles.
- Move your car every `16` milliseconds for a smooth movement.
- The car doesn't have to change directions yet, that's a different feature.

## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Query the element for the car and assign it to a variable in JS
- [x] Apply absolute positioning
- [x] Give x, y variables to car variable
- [x] Add a timer to page for 16 ms
- [x] Move the car image via altering the styling & position values
- [x] Car only moves when space key is pressed

## Example

![user can start their car](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/demos/driving-game/user-can-start-their-car.gif)
