### ISSUE TITLE
user-can-steer-their-car

### ISSUE THREAD

**Issue by vkalinkin** [vkalinkin/driving-game#5]
# Feature

User can steer their car.

## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Have a y variable for car's height
- [x] Modify moveCar function to have if statements based on the car's direction
- [x] Have the if statements correctly modify the x and y variables (east: positive x, west: negative x, north: positive y, south: negative y)

## Example

![user can steer their car](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/demos/driving-game/user-can-steer-their-car.gif)
